### PR TITLE
feat: back architecture config

### PR DESCRIPTION
**Pull request by TommyTraddles**
Primer commit del proyecto, con los ficheros base

### CODE REVIEW

**Review by Protero — APPROVED** [review]
maravilloso 👍

**Review by maidersonn — APPROVED** [review]
Lgtm (looks good to me :+1: )

**Review by maidersonn — CHANGES_REQUESTED** [review]
@TommyTraddles , insert index files into empty folders.

**Review by maidersonn — APPROVED** [review]
:+1:  LGTM

**Pull request merged**
